stages:
  - production_apply
  - production_package

apply:
  stage: production_apply
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  environment: production
  script:
   - echo 'Applying changes to feature configurations in production'
   - aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
   - docker tag e9ae3c220b23 aws_account_id.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag
   - docker push aws_account_id.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag

  only:
    - merge_requests
    - master

package:
  stage: production_package

  script:
    - echo 'Building docker image for production'

  only:
    - merge_requests
    - master